services:
  db:
    image: postgres:16
    container_name: meetup-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meetuplog
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: meetuplog-web
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/meetuplog
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: >
      sh -c "
        echo '🚀 dev server start' &&
        npx prisma generate &&
        npx prisma migrate deploy &&
        npm run dev
      "

volumes:
  db_data: